# Generated by Django 5.0.3 on 2024-03-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('allowed_count', models.IntegerField(default=0)),
                ('not_allowed_count', models.IntegerField(default=0)),
            ],
        ),
    ]
