# Generated by Django 5.0.3 on 2024-03-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todoitem_delete_videocounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='LogsCount',
        ),
    ]
